server:
  port: 8090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    virtual-host: test
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
    publisher-confirms: true
    publisher-returns: true


